import { useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { api } from '../../src/api';
import { colors, money, radius, spacing, typography } from '../../src/theme';
type Order = { orderNumber: string; createdAt: string; totalPence: number; subtotalPence: number; deliveryPence: number; status: string; deliveryAddress: { fullName: string; line1: string; city: string; postcode: string }; items: Array<{ id: string; brandName: string; productName: string; size: string; quantity: number; totalPricePence: number }> };
export default function OrderDetails() { const { orderNumber } = useLocalSearchParams<{ orderNumber: string }>(); const [order, setOrder] = useState<Order>(); useEffect(() => { if (orderNumber) api<Order>(`/orders/${orderNumber}`).then(setOrder).catch(() => undefined); }, [orderNumber]); if (!order) return <View style={s.center}><Text>Loading order…</Text></View>; return <ScrollView style={s.page} contentContainerStyle={s.content}><Text style={s.kicker}>{order.status.replace(/_/g, ' ')}</Text><Text style={s.title}>{order.orderNumber}</Text><Text style={s.date}>Placed {new Date(order.createdAt).toLocaleDateString('en-GB')}</Text><View style={s.card}><Text style={s.heading}>Items</Text>{order.items.map((i) => <View key={i.id} style={s.item}><View><Text style={s.brand}>{i.brandName}</Text><Text style={s.name}>{i.productName}</Text><Text style={s.muted}>Size {i.size} · Qty {i.quantity}</Text></View><Text style={s.price}>{money(i.totalPricePence)}</Text></View>)}</View><View style={s.card}><Text style={s.heading}>Delivery address</Text><Text>{order.deliveryAddress.fullName}</Text><Text>{order.deliveryAddress.line1}</Text><Text>{order.deliveryAddress.city}, {order.deliveryAddress.postcode}</Text></View><View style={s.card}><Row label="Subtotal" value={money(order.subtotalPence)} /><Row label="Delivery" value={order.deliveryPence ? money(order.deliveryPence) : 'Free'} /><Row label="Total" value={money(order.totalPence)} /></View></ScrollView>; }
function Row({ label, value }: { label: string; value: string }) { return <View style={s.row}><Text>{label}</Text><Text style={s.price}>{value}</Text></View>; }
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.paper }, content: { padding: spacing.lg, gap: spacing.md }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, kicker: { ...typography.label, color: colors.success }, title: { ...typography.title }, date: { color: colors.muted }, card: { backgroundColor: colors.white, padding: spacing.md, borderRadius: radius.md, gap: spacing.sm }, heading: { ...typography.heading, marginBottom: spacing.xs }, item: { flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: colors.paper, paddingTop: spacing.sm }, brand: { ...typography.label, color: colors.muted, fontSize: 10 }, name: { fontWeight: '700' }, muted: { color: colors.muted }, price: { fontWeight: '700' }, row: { flexDirection: 'row', justifyContent: 'space-between' } });
