import { Ionicons } from '@expo/vector-icons';
import { Link } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { api } from '../../src/api';
import { colors, money, radius, spacing, typography } from '../../src/theme';
type Order = { orderNumber: string; createdAt: string; totalPence: number; status: string; items: unknown[] };
export default function Orders() { const [orders, setOrders] = useState<Order[]>([]); useEffect(() => { api<Order[]>('/orders').then(setOrders).catch(() => setOrders([])); }, []); return <View style={s.page}>{orders.length ? orders.map((o) => <Link key={o.orderNumber} href={`/orders/${o.orderNumber}`} asChild><Pressable style={s.order}><View><Text style={s.number}>{o.orderNumber}</Text><Text style={s.date}>{new Date(o.createdAt).toLocaleDateString('en-GB')} · {o.items.length} item(s)</Text></View><View style={s.right}><Text style={s.total}>{money(o.totalPence)}</Text><Text style={s.status}>{o.status.replace(/_/g, ' ')}</Text></View><Ionicons name="chevron-forward" size={20} color={colors.muted} /></Pressable></Link>) : <View style={s.empty}><Text style={s.title}>No orders yet</Text><Text style={s.body}>When you place an order, its journey will appear here.</Text></View>}</View>; }
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.paper, padding: spacing.lg, gap: spacing.md }, order: { backgroundColor: colors.white, borderRadius: radius.md, padding: spacing.md, flexDirection: 'row', alignItems: 'center', gap: spacing.md }, number: { fontWeight: '700' }, date: { color: colors.muted, marginTop: 4 }, right: { marginLeft: 'auto', alignItems: 'flex-end' }, total: { fontWeight: '700' }, status: { color: colors.success, fontSize: 11, marginTop: 4 }, empty: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: spacing.sm }, title: { ...typography.title }, body: { ...typography.body, color: colors.muted, textAlign: 'center' } });
