import { Ionicons } from '@expo/vector-icons';
import { Link } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ScreenHeader } from '../../src/components';
import { colors, radius, spacing, typography } from '../../src/theme';

const primary = [
  { icon: 'cube-outline', label: 'Your orders', detail: 'Track deliveries and view receipts', href: '/orders' },
  { icon: 'refresh-outline', label: 'Buy again', detail: 'Find pieces from your order history', href: '/orders' },
  { icon: 'heart-outline', label: 'Saved items', detail: 'Your shortlist, ready when you are', href: '/(tabs)/favourites' },
  { icon: 'sparkles-outline', label: 'Offers just for you', detail: 'Private drops from the Xclusivez studio', href: '/notifications' },
] as const;
const secondary = [
  { icon: 'location-outline', label: 'Delivery addresses', href: '/account/settings' },
  { icon: 'settings-outline', label: 'Account settings', href: '/account/settings' },
  { icon: 'help-circle-outline', label: 'Help & contact', href: '/account/settings' },
  { icon: 'chatbubble-ellipses-outline', label: 'Message us', href: '/support' },
] as const;

export default function Account() { return <SafeAreaView style={s.page} edges={['top']}><ScrollView contentContainerStyle={s.content}><ScreenHeader title="Your account" subtitle="Orders, saved pieces and preferences." /><View style={s.welcome}><View style={s.avatar}><Ionicons name="person-outline" size={27} color={colors.ink} /></View><View style={s.welcomeCopy}><Text style={s.welcomeTitle}>Welcome to Xclusivez.</Text><Text style={s.welcomeBody}>Sign in to sync your orders and saved edit across devices.</Text></View><Link href="/auth/login" asChild><Pressable style={s.signIn}><Text style={s.signInText}>Sign in</Text></Pressable></Link></View><Text style={s.section}>SHOPPING</Text><View style={s.card}>{primary.map((row) => <Link key={row.label} href={row.href} asChild><Pressable style={s.row}><View style={s.rowIcon}><Ionicons name={row.icon} size={21} color={colors.ink} /></View><View style={s.rowCopy}><Text style={s.rowLabel}>{row.label}</Text><Text style={s.rowDetail}>{row.detail}</Text></View><Ionicons name="chevron-forward" size={19} color={colors.muted} /></Pressable></Link>)}</View><Text style={s.section}>ACCOUNT & SUPPORT</Text><View style={s.card}>{secondary.map((row) => <Link key={row.label} href={row.href} asChild><Pressable style={s.row}><View style={s.rowIcon}><Ionicons name={row.icon} size={21} color={colors.ink} /></View><Text style={s.rowLabel}>{row.label}</Text><Ionicons name="chevron-forward" size={19} color={colors.muted} /></Pressable></Link>)}</View><View style={s.membership}><Text style={s.membershipKicker}>XCLUSIVEZ STANDARD</Text><Text style={s.membershipTitle}>Premium style. Real value.</Text><Text style={s.membershipBody}>Authenticity checked, secure Stripe checkout and thoughtful delivery updates.</Text></View></ScrollView></SafeAreaView>; }
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.paper }, content: { paddingBottom: spacing.xl }, welcome: { marginHorizontal: spacing.lg, marginBottom: spacing.lg, padding: spacing.lg, backgroundColor: colors.ink, borderRadius: radius.lg, flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: spacing.md }, avatar: { width: 52, height: 52, borderRadius: 26, backgroundColor: colors.accent, alignItems: 'center', justifyContent: 'center' }, welcomeCopy: { flex: 1, minWidth: 180 }, welcomeTitle: { color: colors.white, fontWeight: '800', fontSize: 16 }, welcomeBody: { color: colors.stone, marginTop: 4, lineHeight: 18 }, signIn: { width: '100%', height: 46, borderRadius: 23, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center' }, signInText: { color: colors.ink, fontWeight: '800' }, section: { ...typography.label, color: colors.muted, marginHorizontal: spacing.lg, marginBottom: spacing.sm, marginTop: spacing.sm }, card: { marginHorizontal: spacing.lg, backgroundColor: colors.white, borderRadius: radius.lg, overflow: 'hidden', marginBottom: spacing.md }, row: { minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.paper }, rowIcon: { width: 38, height: 38, borderRadius: 19, backgroundColor: colors.paper, alignItems: 'center', justifyContent: 'center' }, rowCopy: { flex: 1, gap: 3 }, rowLabel: { fontSize: 16, fontWeight: '700', color: colors.ink }, rowDetail: { fontSize: 12, color: colors.muted }, membership: { marginHorizontal: spacing.lg, marginTop: spacing.md, padding: spacing.lg, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.stone, gap: spacing.xs }, membershipKicker: { ...typography.label, color: colors.accent }, membershipTitle: { ...typography.title }, membershipBody: { ...typography.body, color: colors.muted } });
