import { Ionicons } from '@expo/vector-icons';
import { Link } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { PrimaryButton, ScreenHeader } from '../../src/components';
import { colors, radius, spacing, typography } from '../../src/theme';
const rows = [{ icon: 'cube-outline', label: 'Orders', href: '/orders' }, { icon: 'location-outline', label: 'Delivery addresses', href: '/account/settings' }, { icon: 'heart-outline', label: 'Saved products', href: '/(tabs)/favourites' }, { icon: 'settings-outline', label: 'Account settings', href: '/account/settings' }] as const;
export default function Account() { return <SafeAreaView style={s.page} edges={['top']}><ScreenHeader title="Your account" subtitle="Orders, details and preferences." /><View style={s.guest}><View style={s.avatar}><Ionicons name="person-outline" size={32} color={colors.muted} /></View><Text style={s.guestTitle}>Welcome</Text><Text style={s.guestBody}>Sign in to sync saved pieces, your basket and orders across devices.</Text><Link href="/auth/login" asChild><Pressable style={s.signIn}><Text style={s.signInText}>Sign in</Text></Pressable></Link><Link href="/auth/register" style={s.create}>Create an account</Link></View><View style={s.rows}>{rows.map((r) => <Link key={r.label} href={r.href} asChild><Pressable style={s.row}><Ionicons name={r.icon} size={22} color={colors.ink} /><Text style={s.rowText}>{r.label}</Text><Ionicons name="chevron-forward" size={20} color={colors.muted} /></Pressable></Link>)}</View></SafeAreaView>; }
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.paper }, guest: { margin: spacing.lg, padding: spacing.lg, borderRadius: radius.lg, backgroundColor: colors.white, alignItems: 'center', gap: spacing.sm }, avatar: { width: 70, height: 70, borderRadius: 35, backgroundColor: colors.paper, alignItems: 'center', justifyContent: 'center' }, guestTitle: { ...typography.title }, guestBody: { ...typography.body, color: colors.muted, textAlign: 'center', marginBottom: spacing.sm }, signIn: { minWidth: 210, height: 52, borderRadius: 26, backgroundColor: colors.ink, alignItems: 'center', justifyContent: 'center' }, signInText: { color: colors.white, fontWeight: '700' }, create: { color: colors.ink, fontWeight: '700', padding: spacing.sm }, rows: { marginHorizontal: spacing.lg, backgroundColor: colors.white, borderRadius: radius.lg, overflow: 'hidden' }, row: { height: 62, flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingHorizontal: spacing.md, borderBottomWidth: 1, borderColor: colors.paper }, rowText: { flex: 1, fontSize: 16, fontWeight: '500' } });
