import { Ionicons } from '@expo/vector-icons';
import { Image } from 'expo-image';
import { Link } from 'expo-router';
import { useEffect, useState } from 'react';
import { FlatList, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { BrandMark, ProductCard, SearchBox } from '../../src/components';
import { getProducts } from '../../src/api';
import type { Product } from '../../src/sample-products';
import { colors, spacing, typography } from '../../src/theme';
import { useShop } from '../../src/store';
export default function Home() { const [products, setProducts] = useState<Product[]>([]); const [query, setQuery] = useState(''); const basket = useShop((s) => s.basket); useEffect(() => { getProducts('?sort=newest&limit=10').then(setProducts); }, []); return <SafeAreaView style={s.page} edges={['top']}><ScrollView showsVerticalScrollIndicator={false}><View style={s.top}><BrandMark /><Link href="/basket" asChild><Pressable style={s.bag}><Ionicons name="bag-handle-outline" size={22} /><View style={s.badge}><Text style={s.badgeText}>{basket.reduce((n, i) => n + i.quantity, 0)}</Text></View></Pressable></Link></View><SearchBox value={query} onChangeText={setQuery} /><Link href="/(tabs)/shop" asChild><Pressable style={s.hero}><Image source={{ uri: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=1400' }} style={StyleSheet.absoluteFill} contentFit="cover" /><View style={s.heroShade} /><View style={s.heroCopy}><Text style={s.heroTag}>THE TRAINER EDIT</Text><Text style={s.heroTitle}>Icons, redefined.</Text><Text style={s.heroLink}>Shop the collection →</Text></View></Pressable></Link><Section title="Featured for you" action="See all" /><FlatList data={products.slice(0, 4)} keyExtractor={(p) => p.id} horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.row} renderItem={({ item }) => <View style={{ width: 190 }}><ProductCard product={item} /></View>} /><View style={s.categories}><Text style={s.sectionTitle}>Shop by category</Text><View style={s.categoryRow}><Category title="Trainers" image="https://images.unsplash.com/photo-1495555961986-6d4c1ecb7be3?w=700" /><Category title="Clothing" image="https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=700" /></View></View><Section title="New arrivals" action="Explore" /><View style={s.grid}>{products.slice(2, 6).map((p) => <ProductCard key={p.id} product={p} />)}</View><View style={s.promise}><Text style={s.promiseTitle}>Chosen well. Priced honestly.</Text><Text style={s.promiseBody}>Authenticated products, secure payments and straightforward UK returns.</Text></View></ScrollView></SafeAreaView>; }
function Section({ title, action }: { title: string; action: string }) { return <View style={s.section}><Text style={s.sectionTitle}>{title}</Text><Text style={s.action}>{action}</Text></View>; }
function Category({ title, image }: { title: string; image: string }) { return <Link href={{ pathname: '/(tabs)/shop', params: { category: title.toLowerCase() } }} asChild><Pressable style={s.category}><Image source={{ uri: image }} style={StyleSheet.absoluteFill} contentFit="cover" /><View style={s.catShade} /><Text style={s.catTitle}>{title}</Text></Pressable></Link>; }
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.paper }, top: { paddingHorizontal: spacing.lg, paddingVertical: spacing.md, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, bag: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center' }, badge: { position: 'absolute', right: -2, top: -2, backgroundColor: colors.accent, minWidth: 18, height: 18, borderRadius: 9, alignItems: 'center', justifyContent: 'center' }, badgeText: { color: colors.white, fontSize: 10, fontWeight: '700' }, hero: { height: 410, margin: spacing.lg, borderRadius: 22, overflow: 'hidden', justifyContent: 'flex-end' }, heroShade: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,.27)' }, heroCopy: { padding: spacing.lg, gap: spacing.sm }, heroTag: { ...typography.label, color: '#F1D49D' }, heroTitle: { ...typography.display, color: colors.white, fontSize: 38 }, heroLink: { color: colors.white, fontWeight: '700' }, section: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', paddingHorizontal: spacing.lg, paddingTop: spacing.md, paddingBottom: spacing.sm }, sectionTitle: { ...typography.title, color: colors.ink, fontSize: 22 }, action: { color: colors.muted, fontWeight: '600' }, row: { gap: spacing.md, paddingHorizontal: spacing.lg, paddingBottom: spacing.lg }, categories: { padding: spacing.lg, gap: spacing.md }, categoryRow: { flexDirection: 'row', gap: spacing.md }, category: { flex: 1, height: 215, borderRadius: 16, overflow: 'hidden', justifyContent: 'flex-end' }, catShade: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,.22)' }, catTitle: { color: colors.white, fontSize: 22, fontWeight: '700', padding: spacing.md }, grid: { paddingHorizontal: spacing.lg, flexDirection: 'row', flexWrap: 'wrap', gap: '4%' }, promise: { backgroundColor: colors.ink, marginTop: spacing.xl, padding: spacing.xl, gap: spacing.sm }, promiseTitle: { ...typography.title, color: colors.white }, promiseBody: { ...typography.body, color: colors.stone } });
