import { Ionicons } from '@expo/vector-icons';
import { Link, useLocalSearchParams } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ProductCard, ScreenHeader } from '../../src/components';
import { getProducts } from '../../src/api';
import type { Product } from '../../src/sample-products';
import { colors, radius, spacing } from '../../src/theme';
const sorts = ['Newest', 'Price low to high', 'Price high to low', 'Biggest saving'];
export default function Shop() { const params = useLocalSearchParams<{ category?: string }>(); const [products, setProducts] = useState<Product[]>([]); const [category, setCategory] = useState(params.category ?? 'all'); const [sort, setSort] = useState('Newest'); useEffect(() => { getProducts(category === 'all' ? '' : `?category=${category}`).then(setProducts); }, [category]); const sorted = useMemo(() => [...products].sort((a, b) => sort === sorts[1] ? a.pricePence - b.pricePence : sort === sorts[2] ? b.pricePence - a.pricePence : sort === sorts[3] ? ((b.retailPricePence ?? b.pricePence) - b.pricePence) - ((a.retailPricePence ?? a.pricePence) - a.pricePence) : 0), [products, sort]); return <SafeAreaView style={s.page} edges={['top']}><ScreenHeader title="Shop" subtitle={`${sorted.length} selected pieces`} /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{['all', 'trainers', 'clothing', 'offers'].map((c) => <Pressable key={c} onPress={() => setCategory(c)} style={[s.chip, category === c && s.activeChip]}><Text style={[s.chipText, category === c && s.activeText]}>{c[0]!.toUpperCase() + c.slice(1)}</Text></Pressable>)}</ScrollView><View style={s.tools}><Link href="/filters" asChild><Pressable style={s.tool}><Ionicons name="options-outline" size={18} /><Text>Filter</Text></Pressable></Link><Pressable style={s.tool} onPress={() => setSort(sorts[(sorts.indexOf(sort) + 1) % sorts.length]!)}><Ionicons name="swap-vertical-outline" size={18} /><Text numberOfLines={1}>{sort}</Text></Pressable></View><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.grid}>{sorted.map((p) => <ProductCard key={p.id} product={p} />)}</ScrollView></SafeAreaView>; }
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.paper }, chips: { paddingHorizontal: spacing.lg, gap: spacing.sm, paddingBottom: spacing.md }, chip: { paddingHorizontal: spacing.md, height: 38, borderRadius: radius.pill, borderWidth: 1, borderColor: colors.stone, justifyContent: 'center', backgroundColor: colors.white }, activeChip: { backgroundColor: colors.ink, borderColor: colors.ink }, chipText: { color: colors.ink, fontWeight: '600' }, activeText: { color: colors.white }, tools: { flexDirection: 'row', paddingHorizontal: spacing.lg, gap: spacing.sm, paddingBottom: spacing.md }, tool: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.xs, height: 44, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.stone }, grid: { paddingHorizontal: spacing.lg, flexDirection: 'row', flexWrap: 'wrap', gap: '4%', paddingBottom: spacing.xxl } });
