import { Ionicons } from '@expo/vector-icons';
import { Image } from 'expo-image';
import { Link } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { PrimaryButton } from '../src/components';
import { useShop } from '../src/store';
import { colors, money, radius, spacing, typography } from '../src/theme';
export default function Basket() { const { basket, setQuantity } = useShop(); const subtotal = basket.reduce((n, i) => n + i.product.pricePence * i.quantity, 0); const delivery = subtotal >= 10000 ? 0 : 499; return <View style={s.page}>{basket.length ? <><ScrollView contentContainerStyle={s.list}>{basket.map((item) => <View key={item.variantId} style={s.item}><Image source={{ uri: item.product.imageUrl }} style={s.image} contentFit="cover" /><View style={s.itemBody}><Text style={s.brand}>{item.product.brand}</Text><Text style={s.name}>{item.product.name}</Text><Text style={s.meta}>Size {item.size}</Text><Text style={s.price}>{money(item.product.pricePence)}</Text><View style={s.quantity}><Pressable onPress={() => setQuantity(item.variantId, item.quantity - 1)}><Ionicons name="remove" size={18} /></Pressable><Text style={s.qty}>{item.quantity}</Text><Pressable onPress={() => setQuantity(item.variantId, item.quantity + 1)}><Ionicons name="add" size={18} /></Pressable></View></View><Pressable onPress={() => setQuantity(item.variantId, 0)}><Ionicons name="close" size={20} color={colors.muted} /></Pressable></View>)}</ScrollView><View style={s.summary}><Row label="Subtotal" value={money(subtotal)} /><Row label="Delivery" value={delivery ? money(delivery) : 'Free'} /><View style={s.rule} /><Row label="Total" value={money(subtotal + delivery)} strong /><Link href="/checkout/delivery" asChild><Pressable style={s.checkout}><Text style={s.checkoutText}>Continue to delivery</Text></Pressable></Link><Text style={s.note}>Taxes included. Final stock and pricing checked securely at checkout.</Text></View></> : <View style={s.empty}><Text style={s.emptyTitle}>Your basket is waiting</Text><Text style={s.emptyText}>Add something exceptional and it’ll appear here.</Text><Link href="/(tabs)/shop" asChild><Pressable style={s.shop}><Text style={s.shopText}>Shop now</Text></Pressable></Link></View>}</View>; }
function Row({ label, value, strong }: { label: string; value: string; strong?: boolean }) { return <View style={s.row}><Text style={strong && s.strong}>{label}</Text><Text style={strong && s.strong}>{value}</Text></View>; }
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.paper }, list: { padding: spacing.lg, gap: spacing.md }, item: { flexDirection: 'row', gap: spacing.md, backgroundColor: colors.white, borderRadius: radius.md, padding: spacing.sm }, image: { width: 105, height: 125, borderRadius: radius.sm }, itemBody: { flex: 1, gap: 3 }, brand: { ...typography.label, color: colors.muted, fontSize: 10 }, name: { fontWeight: '700', fontSize: 16 }, meta: { color: colors.muted }, price: { fontWeight: '700', marginTop: 3 }, quantity: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, marginTop: 'auto' }, qty: { minWidth: 18, textAlign: 'center', fontWeight: '700' }, summary: { padding: spacing.lg, backgroundColor: colors.white, gap: spacing.sm, borderTopWidth: 1, borderTopColor: colors.stone }, row: { flexDirection: 'row', justifyContent: 'space-between' }, strong: { fontWeight: '800', fontSize: 18 }, rule: { height: 1, backgroundColor: colors.stone, marginVertical: spacing.xs }, checkout: { height: 54, borderRadius: 27, backgroundColor: colors.ink, alignItems: 'center', justifyContent: 'center', marginTop: spacing.sm }, checkoutText: { color: colors.white, fontWeight: '700' }, note: { color: colors.muted, fontSize: 11, textAlign: 'center' }, empty: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: spacing.xl, gap: spacing.sm }, emptyTitle: { ...typography.title }, emptyText: { ...typography.body, color: colors.muted, textAlign: 'center' }, shop: { backgroundColor: colors.ink, borderRadius: 26, paddingHorizontal: spacing.xl, paddingVertical: spacing.md, marginTop: spacing.md }, shopText: { color: colors.white, fontWeight: '700' } });
