import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { api } from '../../src/api';
import { Field, PrimaryButton } from '../../src/components';
import { colors, money, radius, spacing, typography } from '../../src/theme';

type Order = { orderNumber: string; totalPence: number; status: string; user?: { email: string }; createdAt: string };
export default function AdminDashboard() {
  const router = useRouter(); const [orders, setOrders] = useState<Order[]>([]); const [loading, setLoading] = useState(false); const [noticeLoading, setNoticeLoading] = useState(false);
  const [notice, setNotice] = useState({ title: 'Offers just for you', body: '' });
  const [product, setProduct] = useState({ name: '', slug: '', description: '', brandName: '', categoryName: 'Trainers', colour: '', baseSku: '', pricePence: '', retailPricePence: '', imageUrl: '', size: 'One size', quantity: '1' });
  const set = (key: keyof typeof product) => (value: string) => setProduct((current) => ({ ...current, [key]: value }));
  useEffect(() => { api<Order[]>('/admin/orders').then(setOrders).catch(() => undefined); }, []);
  const publish = async () => { try { setLoading(true); const created = await api<{ id: string }>('/admin/products', { method: 'POST', body: JSON.stringify({ name: product.name, slug: product.slug, description: product.description, brandName: product.brandName, categoryName: product.categoryName, colour: product.colour, baseSku: product.baseSku, pricePence: Number(product.pricePence), retailPricePence: product.retailPricePence ? Number(product.retailPricePence) : undefined, status: 'ACTIVE', featured: true }) }); if (product.imageUrl) await api(`/admin/products/${created.id}/images`, { method: 'POST', body: JSON.stringify({ url: product.imageUrl, altText: product.name }) }); await api(`/admin/products/${created.id}/variants`, { method: 'POST', body: JSON.stringify({ size: product.size, sku: `${product.baseSku}-${product.size}`.replace(/\s+/g, '-'), quantity: Number(product.quantity) }) }); Alert.alert('Published', `${product.name} is now live in the shop.`); } catch (error) { Alert.alert('Could not publish', error instanceof Error ? error.message : 'Please check the product details'); } finally { setLoading(false); } };
  const sendNotice = async () => { try { setNoticeLoading(true); const result = await api<{ sent: number }>('/notifications/admin/send', { method: 'POST', body: JSON.stringify(notice) }); Alert.alert('Offer alert sent', `${result.sent} device(s) will receive it.`); } catch (error) { Alert.alert('Could not send alert', error instanceof Error ? error.message : 'Please try again'); } finally { setNoticeLoading(false); } };
  return <ScrollView style={s.page} contentContainerStyle={s.content}><Text style={s.kicker}>XCLUSIVEZ 4 YOU · ADMIN</Text><Text style={s.title}>Studio overview</Text><View style={s.metric}><View style={s.metricIcon}><Ionicons name="cube-outline" size={22} color={colors.accent} /></View><View><Text style={s.metricValue}>{orders.length}</Text><Text style={s.metricLabel}>orders to review</Text></View></View><View style={s.card}><Text style={s.heading}>Publish a product</Text><Text style={s.helper}>Add a product, its hero image URL and first available size.</Text><View style={s.form}>{(['name', 'slug', 'brandName', 'categoryName', 'colour', 'baseSku', 'pricePence', 'retailPricePence', 'imageUrl', 'size', 'quantity'] as const).map((key) => <Field key={key} label={key === 'imageUrl' ? 'Hero image URL' : key.replace(/([A-Z])/g, ' $1')} value={product[key]} onChangeText={set(key)} keyboardType={key.includes('Pence') || key === 'quantity' ? 'number-pad' : 'default'} />)}<Field label="Description" value={product.description} onChangeText={set('description')} multiline /><PrimaryButton loading={loading} disabled={!product.name || !product.slug || !product.brandName || !product.baseSku || !product.pricePence || !product.imageUrl} onPress={publish}>Publish to shop</PrimaryButton></View></View><View style={s.card}><Text style={s.heading}>Offers just for you</Text><Text style={s.helper}>Send a targeted push notification to every registered shopper.</Text><Field label="Notification title" value={notice.title} onChangeText={(title) => setNotice((n) => ({ ...n, title }))} /><Field label="Message" value={notice.body} onChangeText={(body) => setNotice((n) => ({ ...n, body }))} multiline placeholder="A private drop is waiting..." /><PrimaryButton loading={noticeLoading} disabled={!notice.title || !notice.body} onPress={sendNotice}>Send offer alert</PrimaryButton></View><View style={s.card}><Text style={s.heading}>Recent orders</Text>{orders.slice(0, 8).map((order) => <View key={order.orderNumber} style={s.order}><View><Text style={s.orderNumber}>{order.orderNumber}</Text><Text style={s.helper}>{order.user?.email ?? 'Customer'} · {new Date(order.createdAt).toLocaleDateString('en-GB')}</Text></View><View style={s.orderRight}><Text style={s.total}>{money(order.totalPence)}</Text><Text style={s.status}>{order.status.replace(/_/g, ' ')}</Text></View></View>)}</View></ScrollView>;
}
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.paper }, content: { padding: spacing.lg, gap: spacing.md }, kicker: { ...typography.label, color: colors.accent }, title: { ...typography.display, color: colors.ink }, metric: { backgroundColor: colors.ink, borderRadius: radius.lg, padding: spacing.lg, flexDirection: 'row', gap: spacing.md, alignItems: 'center' }, metricIcon: { width: 46, height: 46, borderRadius: 23, backgroundColor: '#243018', alignItems: 'center', justifyContent: 'center' }, metricValue: { color: colors.white, fontSize: 24, fontWeight: '800' }, metricLabel: { color: colors.stone }, card: { backgroundColor: colors.white, borderRadius: radius.lg, padding: spacing.lg, gap: spacing.sm }, heading: { ...typography.title }, helper: { color: colors.muted, lineHeight: 19 }, form: { gap: spacing.sm }, order: { paddingVertical: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.paper, flexDirection: 'row', justifyContent: 'space-between' }, orderNumber: { fontWeight: '700' }, orderRight: { alignItems: 'flex-end' }, total: { fontWeight: '800' }, status: { color: colors.success, fontSize: 11, marginTop: 3 } });
