import { useEffect, useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { api } from '../../src/api';
import { Field, PrimaryButton } from '../../src/components';
import { colors, radius, spacing, typography } from '../../src/theme';

type Message = { id: string; body: string; senderType: 'CUSTOMER' | 'ADMIN'; createdAt: string };
type Thread = { id: string; subject: string; status: string; user: { email: string; firstName: string }; messages: Message[] };
export default function AdminSupport() { const [threads, setThreads] = useState<Thread[]>([]); const [selected, setSelected] = useState<Thread>(); const [body, setBody] = useState(''); const [sending, setSending] = useState(false); const load = () => api<Thread[]>('/support/admin/threads').then(setThreads).catch(() => undefined); useEffect(() => { load(); const timer = setInterval(load, 5000); return () => clearInterval(timer); }, []); const send = async () => { if (!selected || !body.trim()) return; try { setSending(true); const updated = await api<Thread>(`/support/threads/${selected.id}/messages`, { method: 'POST', body: JSON.stringify({ body }) }); setSelected(updated); setBody(''); load(); } catch (error) { Alert.alert('Could not send', error instanceof Error ? error.message : 'Please try again'); } finally { setSending(false); } }; return <KeyboardAvoidingView style={s.page} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><Text style={s.kicker}>XCLUSIVEZ 4 YOU · SUPPORT</Text><Text style={s.title}>Customer messages</Text>{selected ? <><Pressable onPress={() => setSelected(undefined)}><Text style={s.back}>‹ All conversations</Text></Pressable><View style={s.selected}><Text style={s.subject}>{selected.subject}</Text><Text style={s.muted}>{selected.user.firstName} · {selected.user.email}</Text></View><ScrollView contentContainerStyle={s.messages}>{selected.messages.map((message) => <View key={message.id} style={[s.bubble, message.senderType === 'ADMIN' ? s.admin : s.customer]}><Text style={s.label}>{message.senderType === 'ADMIN' ? 'Studio' : selected.user.firstName}</Text><Text style={message.senderType === 'ADMIN' ? s.darkText : s.lightText}>{message.body}</Text></View>)}</ScrollView><View style={s.composer}><Field label="Reply" value={body} onChangeText={setBody} multiline placeholder="Write a helpful reply..." /><PrimaryButton loading={sending} disabled={!body.trim()} onPress={send}>Reply to customer</PrimaryButton></View></> : <ScrollView contentContainerStyle={s.list}>{threads.length ? threads.map((thread) => <Pressable key={thread.id} style={s.thread} onPress={() => api<Thread>(`/support/threads/${thread.id}`).then(setSelected)}><View style={s.threadCopy}><Text style={s.subject}>{thread.subject}</Text><Text style={s.muted}>{thread.user.firstName} · {thread.user.email}</Text><Text style={s.muted}>{thread.messages[0]?.body ?? 'No messages'}</Text></View><Text style={s.status}>{thread.status}</Text></Pressable>) : <Text style={s.muted}>No customer conversations yet.</Text>}</ScrollView>}</KeyboardAvoidingView>; }
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.paper, padding: spacing.lg, gap: spacing.md }, kicker: { ...typography.label, color: colors.accent }, title: { ...typography.display }, back: { color: colors.ink, fontWeight: '700' }, selected: { backgroundColor: colors.white, borderRadius: radius.md, padding: spacing.md, gap: 4 }, subject: { fontWeight: '800', fontSize: 16 }, muted: { color: colors.muted, lineHeight: 19 }, list: { gap: spacing.sm, paddingBottom: spacing.xl }, thread: { backgroundColor: colors.white, borderRadius: radius.md, padding: spacing.md, flexDirection: 'row', gap: spacing.md }, threadCopy: { flex: 1, gap: 3 }, status: { color: colors.success, fontSize: 11, fontWeight: '700' }, messages: { gap: spacing.sm, paddingVertical: spacing.md }, bubble: { maxWidth: '88%', padding: spacing.md, borderRadius: radius.md, gap: 4 }, customer: { alignSelf: 'flex-start', backgroundColor: colors.ink }, admin: { alignSelf: 'flex-end', backgroundColor: colors.white }, label: { fontSize: 10, fontWeight: '800', color: colors.accent }, lightText: { color: colors.white, lineHeight: 19 }, darkText: { color: colors.ink, lineHeight: 19 }, composer: { gap: spacing.sm, backgroundColor: colors.white, padding: spacing.md, marginHorizontal: -spacing.lg }, });
