import { Ionicons } from '@expo/vector-icons';
import { Image } from 'expo-image';
import { Link } from 'expo-router';
import { useId, type PropsWithChildren } from 'react';
import { ActivityIndicator, InputAccessoryView, Keyboard, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import type { Product } from './sample-products';
import { colors, money, radius, spacing, typography } from './theme';
import { useShop } from './store';

export function BrandMark({ inverse = false }: { inverse?: boolean }) { return <View style={styles.brandMark}><Image source={require('../assets/brand-logo.png')} style={styles.brandLogo} contentFit="contain" /><Text style={[styles.brandWordmark, inverse && { color: colors.white }]}>XCLUSIVEZ 4 YOU</Text></View>; }
export function ScreenHeader({ title, subtitle }: { title: string; subtitle?: string }) { return <View style={styles.header}><Text style={styles.title}>{title}</Text>{subtitle ? <Text style={styles.subtitle}>{subtitle}</Text> : null}</View>; }
export function SearchBox({ value, onChangeText, onSubmit }: { value: string; onChangeText: (v: string) => void; onSubmit?: () => void }) { return <View style={styles.search}><Ionicons name="search" size={20} color={colors.muted} /><TextInput value={value} onChangeText={onChangeText} onSubmitEditing={onSubmit} placeholder="Search trainers, clothing, brands" placeholderTextColor={colors.muted} style={styles.searchInput} returnKeyType="search" /></View>; }
export function ProductCard({ product }: { product: Product }) { const { favourites, toggleFavourite } = useShop(); const saving = (product.retailPricePence ?? product.pricePence) - product.pricePence; return <View style={styles.card}><Link href={{ pathname: '/product/[slug]', params: { slug: product.slug } }} asChild><Pressable><Image source={{ uri: product.imageUrl }} style={styles.cardImage} contentFit="cover" transition={180} /><View style={styles.cardBody}><Text style={styles.brand}>{product.brand}</Text><Text style={styles.productName} numberOfLines={2}>{product.name}</Text><View style={styles.priceRow}><Text style={styles.price}>{money(product.pricePence)}</Text>{product.retailPricePence ? <Text style={styles.was}>{money(product.retailPricePence)}</Text> : null}</View>{saving > 0 ? <Text style={styles.saving}>Save {money(saving)}</Text> : null}</View></Pressable></Link><Pressable accessibilityLabel="Toggle favourite" style={styles.heart} onPress={() => toggleFavourite(product.id)}><Ionicons name={favourites.includes(product.id) ? 'heart' : 'heart-outline'} size={21} color={favourites.includes(product.id) ? colors.danger : colors.ink} /></Pressable></View>; }
export function PrimaryButton({ children, onPress, disabled, loading }: PropsWithChildren<{ onPress?: () => void; disabled?: boolean; loading?: boolean }>) { return <Pressable onPress={onPress} disabled={disabled || loading} style={({ pressed }) => [styles.button, (disabled || loading) && styles.disabled, pressed && { opacity: .82 }]}>{loading ? <ActivityIndicator color={colors.white} /> : <Text style={styles.buttonText}>{children}</Text>}</Pressable>; }
export function Field({ label, style, ...props }: { label: string } & React.ComponentProps<typeof TextInput>) {
  const accessoryId = `keyboard-${useId().replace(/:/g, '')}`;
  return <><View style={{ gap: spacing.xs }}><Text style={styles.fieldLabel}>{label}</Text><TextInput placeholderTextColor={colors.muted} style={[styles.field, props.multiline && styles.multilineField, style]} inputAccessoryViewID={Platform.OS === 'ios' ? accessoryId : undefined} {...props} /></View>{Platform.OS === 'ios' ? <InputAccessoryView nativeID={accessoryId}><View style={styles.keyboardToolbar}><Pressable accessibilityRole="button" accessibilityLabel="Hide keyboard" onPress={Keyboard.dismiss} style={styles.keyboardDone}><Text style={styles.keyboardDoneText}>Done</Text></Pressable></View></InputAccessoryView> : null}</>;
}

const styles = StyleSheet.create({ brandMark: { alignItems: 'center', gap: 5 }, brandLogo: { width: 92, height: 92 }, brandWordmark: { ...typography.label, color: colors.accent, letterSpacing: 2 }, eyebrow: { ...typography.label, color: colors.accent }, mark: { fontSize: 29, fontWeight: '700', color: colors.ink, letterSpacing: -1 }, header: { paddingHorizontal: spacing.lg, paddingTop: spacing.md, paddingBottom: spacing.md, gap: spacing.xs }, title: { ...typography.display, color: colors.ink }, subtitle: { ...typography.body, color: colors.muted }, search: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginHorizontal: spacing.lg, backgroundColor: colors.white, borderRadius: radius.pill, paddingHorizontal: spacing.md, height: 50, borderWidth: 1, borderColor: colors.stone }, searchInput: { flex: 1, fontSize: 15, color: colors.ink }, card: { width: '48%', backgroundColor: colors.white, borderRadius: radius.md, overflow: 'hidden', position: 'relative' }, cardImage: { width: '100%', aspectRatio: .82, backgroundColor: colors.stone }, cardBody: { padding: spacing.sm, paddingBottom: spacing.md, gap: 4 }, brand: { ...typography.label, color: colors.muted, fontSize: 10 }, productName: { fontSize: 15, lineHeight: 19, fontWeight: '600', color: colors.ink, minHeight: 38 }, priceRow: { flexDirection: 'row', gap: spacing.xs, alignItems: 'center' }, price: { fontWeight: '700', fontSize: 15, color: colors.ink }, was: { color: colors.muted, textDecorationLine: 'line-through', fontSize: 12 }, saving: { color: colors.success, fontWeight: '600', fontSize: 12 }, heart: { position: 'absolute', top: 9, right: 9, width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,.92)' }, button: { minHeight: 54, borderRadius: radius.pill, backgroundColor: colors.ink, alignItems: 'center', justifyContent: 'center', paddingHorizontal: spacing.lg }, disabled: { opacity: .45 }, buttonText: { color: colors.white, fontWeight: '700', fontSize: 15 }, fieldLabel: { ...typography.label, color: colors.muted }, field: { height: 52, borderWidth: 1, borderColor: colors.stone, borderRadius: radius.md, paddingHorizontal: spacing.md, fontSize: 16, color: colors.ink, backgroundColor: colors.white }, multilineField: { minHeight: 96, height: 'auto', paddingTop: spacing.md, textAlignVertical: 'top' }, keyboardToolbar: { minHeight: 45, flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', paddingHorizontal: spacing.md, backgroundColor: colors.paper, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.stone }, keyboardDone: { paddingHorizontal: spacing.sm, paddingVertical: spacing.xs }, keyboardDoneText: { color: colors.ink, fontWeight: '800', fontSize: 16 } });
