import * as SecureStore from 'expo-secure-store';
import { Link, useRouter } from 'expo-router';
import { useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import { api } from '../../src/api';
import { registerForOfferNotifications } from '../../src/notifications';
import { Field, PrimaryButton } from '../../src/components';
import { colors, spacing, typography } from '../../src/theme';
export default function Login() { const router = useRouter(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [loading, setLoading] = useState(false); const submit = async () => { try { setLoading(true); const data = await api<{ accessToken: string; refreshToken: string }>('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); await Promise.all([SecureStore.setItemAsync('accessToken', data.accessToken), SecureStore.setItemAsync('refreshToken', data.refreshToken)]); await registerForOfferNotifications().catch(() => undefined); router.replace('/(tabs)/account'); } catch (e) { Alert.alert('Unable to sign in', e instanceof Error ? e.message : 'Please try again'); } finally { setLoading(false); } }; return <KeyboardAvoidingView style={s.page} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={s.copy}><Text style={s.title}>Welcome back.</Text><Text style={s.subtitle}>Your saved pieces, basket and orders are waiting.</Text></View><View style={s.form}><Field label="Email address" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" /><Field label="Password" value={password} onChangeText={setPassword} secureTextEntry /><Link href="/auth/forgot-password" style={s.forgot}>Forgot password?</Link><PrimaryButton onPress={submit} loading={loading} disabled={!email || !password}>Sign in</PrimaryButton><Text style={s.join}>New here? <Link href="/auth/register" style={s.link}>Create an account</Link></Text></View></KeyboardAvoidingView>; }
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.paper, padding: spacing.lg }, copy: { marginTop: spacing.xl, gap: spacing.sm }, title: { ...typography.display }, subtitle: { ...typography.body, color: colors.muted }, form: { gap: spacing.md, marginTop: spacing.xl }, forgot: { color: colors.ink, textAlign: 'right', fontWeight: '600' }, join: { textAlign: 'center', color: colors.muted }, link: { color: colors.ink, fontWeight: '700' } });
