import * as SecureStore from 'expo-secure-store';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, View } from 'react-native';
import { api } from '../../src/api';
import { Field, PrimaryButton } from '../../src/components';
import { colors, spacing, typography } from '../../src/theme';
export default function Register() { const router = useRouter(); const [form, setForm] = useState({ firstName: '', lastName: '', email: '', password: '' }); const [loading, setLoading] = useState(false); const set = (key: keyof typeof form) => (value: string) => setForm((v) => ({ ...v, [key]: value })); const submit = async () => { try { setLoading(true); const data = await api<{ accessToken: string; refreshToken: string }>('/auth/register', { method: 'POST', body: JSON.stringify(form) }); await SecureStore.setItemAsync('accessToken', data.accessToken); await SecureStore.setItemAsync('refreshToken', data.refreshToken); router.replace('/(tabs)'); } catch (e) { Alert.alert('Unable to register', e instanceof Error ? e.message : 'Please check your details'); } finally { setLoading(false); } }; return <KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView style={s.page} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={s.title}>Your edit starts here.</Text><Text style={s.subtitle}>Create an account to save products and follow every order.</Text><View style={s.form}><Field label="First name" value={form.firstName} onChangeText={set('firstName')} /><Field label="Last name" value={form.lastName} onChangeText={set('lastName')} /><Field label="Email address" value={form.email} onChangeText={set('email')} autoCapitalize="none" keyboardType="email-address" /><Field label="Password" value={form.password} onChangeText={set('password')} secureTextEntry /><Text style={s.hint}>Use at least 10 characters with upper-case, lower-case and a number.</Text><PrimaryButton onPress={submit} loading={loading} disabled={Object.values(form).some((v) => !v)}>Create account</PrimaryButton><Text style={s.terms}>By continuing, you agree to the Terms and Privacy Policy.</Text></View></ScrollView></KeyboardAvoidingView>; }
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.paper }, content: { padding: spacing.lg, paddingBottom: spacing.xxl }, title: { ...typography.display, marginTop: spacing.md }, subtitle: { ...typography.body, color: colors.muted, marginTop: spacing.sm }, form: { gap: spacing.md, marginTop: spacing.xl }, hint: { color: colors.muted, fontSize: 12 }, terms: { color: colors.muted, textAlign: 'center', fontSize: 12 } });
