import { Ionicons } from '@expo/vector-icons';
import { Link, useRouter } from 'expo-router';
import { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { api } from '../../src/api';
import { Field, PrimaryButton } from '../../src/components';
import { colors, radius, spacing, typography } from '../../src/theme';

type Thread = { id: string; subject: string; status: string; updatedAt: string; messages: Array<{ body: string; createdAt: string }> };
export default function SupportInbox() { const router = useRouter(); const [threads, setThreads] = useState<Thread[]>([]); const [compose, setCompose] = useState(false); const [subject, setSubject] = useState(''); const [body, setBody] = useState(''); const [loading, setLoading] = useState(false); const load = () => api<Thread[]>('/support/threads').then(setThreads).catch(() => setThreads([])); useEffect(() => { load(); }, []); const create = async () => { try { setLoading(true); const thread = await api<Thread>('/support/threads', { method: 'POST', body: JSON.stringify({ subject, body }) }); setCompose(false); setSubject(''); setBody(''); router.push(`/support/${thread.id}`); } catch (error) { Alert.alert('Could not send message', error instanceof Error ? error.message : 'Please sign in and try again'); } finally { setLoading(false); } }; return <ScrollView style={s.page} contentContainerStyle={s.content}><View style={s.hero}><Ionicons name="chatbubble-ellipses-outline" size={27} color={colors.accent} /><Text style={s.kicker}>XCLUSIVEZ SUPPORT</Text><Text style={s.title}>Send us a message.</Text><Text style={s.body}>Our studio team can help with sizing, authenticity, delivery, offers and orders.</Text><Pressable style={s.heroButton} onPress={() => setCompose(true)}><Text style={s.heroButtonText}>Start a conversation</Text></Pressable></View>{threads.length ? <View style={s.card}>{threads.map((thread) => <Link key={thread.id} href={`/support/${thread.id}`} asChild><Pressable style={s.thread}><View style={s.threadIcon}><Ionicons name="chatbubble-outline" size={19} color={colors.ink} /></View><View style={s.threadCopy}><Text style={s.subject}>{thread.subject}</Text><Text style={s.preview} numberOfLines={1}>{thread.messages[0]?.body ?? 'Open conversation'}</Text><Text style={s.date}>{new Date(thread.updatedAt).toLocaleDateString('en-GB')} · {thread.status.toLowerCase()}</Text></View><Ionicons name="chevron-forward" size={18} color={colors.muted} /></Pressable></Link>)}</View> : <View style={s.empty}><Text style={s.emptyTitle}>No conversations yet</Text><Text style={s.preview}>Send us a message and the studio team will reply here.</Text></View>}<View style={s.card}><Text style={s.heading}>Chat is available in the app</Text><Text style={s.preview}>Replies refresh automatically while you’re viewing a conversation.</Text></View><View>{compose ? <View style={s.compose}><Text style={s.heading}>New conversation</Text><Field label="Subject" value={subject} onChangeText={setSubject} placeholder="How can we help?" /><Field label="Message" value={body} onChangeText={setBody} multiline placeholder="Tell us what you need..." /><PrimaryButton loading={loading} disabled={!subject.trim() || !body.trim()} onPress={create}>Send to the studio</PrimaryButton><Pressable onPress={() => setCompose(false)}><Text style={s.cancel}>Cancel</Text></Pressable></View> : null}</View></ScrollView>; }
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.paper }, content: { padding: spacing.lg, gap: spacing.md }, hero: { backgroundColor: colors.ink, borderRadius: radius.lg, padding: spacing.lg, gap: spacing.sm }, kicker: { ...typography.label, color: colors.accent, marginTop: spacing.sm }, title: { ...typography.display, color: colors.white }, body: { ...typography.body, color: colors.stone }, heroButton: { height: 50, borderRadius: 25, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center', marginTop: spacing.sm }, heroButtonText: { color: colors.ink, fontWeight: '800' }, card: { backgroundColor: colors.white, borderRadius: radius.lg, overflow: 'hidden' }, thread: { minHeight: 82, flexDirection: 'row', alignItems: 'center', gap: spacing.md, padding: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.paper }, threadIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.paper, alignItems: 'center', justifyContent: 'center' }, threadCopy: { flex: 1, gap: 3 }, subject: { fontWeight: '800', fontSize: 15 }, preview: { color: colors.muted, lineHeight: 19 }, date: { color: colors.muted, fontSize: 11 }, empty: { padding: spacing.lg, alignItems: 'center', gap: spacing.xs }, emptyTitle: { ...typography.title }, heading: { ...typography.title, padding: spacing.lg, paddingBottom: spacing.xs }, compose: { backgroundColor: colors.white, borderRadius: radius.lg, padding: spacing.lg, gap: spacing.sm }, cancel: { textAlign: 'center', fontWeight: '700', padding: spacing.sm } });
