import { CardField, useConfirmPayment } from '@stripe/stripe-react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { api } from '../../src/api';
import { PrimaryButton } from '../../src/components';
import { useShop } from '../../src/store';
import { colors, money, radius, spacing, typography } from '../../src/theme';
export default function Payment() { const router = useRouter(); const params = useLocalSearchParams<{ delivery: string }>(); const basket = useShop((s) => s.basket); const clear = useShop((s) => s.clearBasket); const { confirmPayment } = useConfirmPayment(); const [ready, setReady] = useState(false); const [loading, setLoading] = useState(false); const subtotal = basket.reduce((n, i) => n + i.product.pricePence * i.quantity, 0); const deliveryCost = subtotal >= 10000 ? 0 : 499; const pay = async () => { try { setLoading(true); const delivery = JSON.parse(params.delivery ?? '{}'); const intent = await api<{ orderNumber: string; clientSecret: string }>('/checkout/payment-intent', { method: 'POST', body: JSON.stringify({ ...delivery, deliveryMethodId: 'standard' }) }); const result = await confirmPayment(intent.clientSecret, { paymentMethodType: 'Card' }); if (result.error) throw new Error(result.error.message); clear(); router.replace({ pathname: '/checkout/confirmation', params: { orderNumber: intent.orderNumber } }); } catch (e) { Alert.alert('Payment not completed', e instanceof Error ? e.message : 'Please try again'); } finally { setLoading(false); } }; return <View style={s.page}><Text style={s.step}>STEP 4 OF 4</Text><Text style={s.title}>Secure payment</Text><Text style={s.body}>Card details are handled by Stripe and are never stored by Exclusives for You.</Text><View style={s.methods}><Text style={s.heading}>Card</Text><CardField postalCodeEnabled={false} onCardChange={(v) => setReady(Boolean(v.complete))} style={s.card} cardStyle={{ backgroundColor: colors.white, textColor: colors.ink }} /><Text style={s.wallet}>Secure card payment powered by Stripe.</Text></View><View style={s.summary}><Row label="Subtotal" value={money(subtotal)} /><Row label="Delivery" value={deliveryCost ? money(deliveryCost) : 'Free'} /><Row label="Total" value={money(subtotal + deliveryCost)} strong /></View><PrimaryButton onPress={pay} loading={loading} disabled={!ready || !basket.length}>Pay {money(subtotal + deliveryCost)}</PrimaryButton></View>; }
function Row({ label, value, strong }: { label: string; value: string; strong?: boolean }) { return <View style={s.row}><Text style={strong && s.strong}>{label}</Text><Text style={strong && s.strong}>{value}</Text></View>; }
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.paper, padding: spacing.lg, gap: spacing.md }, step: { ...typography.label, color: colors.accent }, title: { ...typography.display }, body: { ...typography.body, color: colors.muted }, methods: { backgroundColor: colors.white, borderRadius: radius.lg, padding: spacing.md, marginTop: spacing.md }, heading: { ...typography.heading }, card: { height: 54, marginTop: spacing.md }, wallet: { color: colors.muted, fontSize: 12, marginTop: spacing.sm }, summary: { backgroundColor: colors.white, borderRadius: radius.lg, padding: spacing.md, gap: spacing.sm, marginVertical: spacing.md }, row: { flexDirection: 'row', justifyContent: 'space-between' }, strong: { fontSize: 18, fontWeight: '800' } });
